export interface ReferencePage {
  slug: string;
  start: string;
  title: string;
  summary: string;
  group: string;
}

export const REFERENCE_GROUPS = ['Basics', 'Board', 'Parts', 'Schematic and layout', 'Simulation', 'Output'];

export const REFERENCE: ReferencePage[] = [
  {
    slug: 'overview',
    start: '# agentee file format',
    title: 'Project files',
    summary: 'A project is a directory of TOML files loaded by their suffix: boards, symbols, footprints, schematics, layouts and simulations.',
    group: 'Basics',
  },
  {
    slug: 'edit',
    start: '## Editing with `agentee edit`',
    title: 'Editing with agentee edit',
    summary: 'The commands that write every key of a schematic, layout or board spec, keep the file’s comments, and check what they changed.',
    group: 'Basics',
  },
  {
    slug: 'units',
    start: '## Units and coordinates',
    title: 'Units and coordinates',
    summary: 'Millimetres by default, unit strings for everything else, Y growing down and rotation counter-clockwise on screen.',
    group: 'Basics',
  },
  {
    slug: 'workflow',
    start: '## Workflow',
    title: 'Workflow',
    summary: 'The order a design is built in, from importing parts to writing the fab package.',
    group: 'Basics',
  },
  {
    slug: 'board',
    start: '## Board spec (`*.board.toml`)',
    title: 'Board spec',
    summary: 'The *.board.toml file: fab preset, outline and cutouts, stackup, via types and net classes with impedance and current targets.',
    group: 'Board',
  },
  {
    slug: 'stackups',
    start: '### Stackup presets',
    title: 'Stackup presets',
    summary: 'Every JLCPCB impedance build, the PCBWay standard builds and two generic HDI stackups, named by the fab’s own code.',
    group: 'Board',
  },
  {
    slug: 'lamination',
    start: '### Lamination',
    title: 'Lamination',
    summary: 'The build-up sequence of presses and drill steps, derived from the stackup or listed by hand, that decides which vias can be drilled.',
    group: 'Board',
  },
  {
    slug: 'vias',
    start: '### Via types',
    title: 'Via types',
    summary: 'Through, blind, buried and microvias, stacked and skip vias, controlled depth drilling, backdrills and IPC-4761 via fill.',
    group: 'Board',
  },
  {
    slug: 'rules',
    start: '### Rules',
    title: 'Fab rules',
    summary: 'Every fab rule key, and the values of the generic, jlcpcb and hdi presets with the line of the fab’s capability page each one comes from.',
    group: 'Board',
  },
  {
    slug: 'drc',
    start: '### Design rule checks',
    title: 'Design rule checks',
    summary: 'Every layout rule with its id, severity and the condition it runs under: copper, drills, mask, silk, assembly, zones, signals, test access and placement.',
    group: 'Board',
  },
  {
    slug: 'impedance',
    start: '### What check computes',
    title: 'Impedance and loss',
    summary: 'Trace geometry per class and layer, closed form and field solved impedance, differential pairs, and the loss model with roughness and ENIG.',
    group: 'Board',
  },
  {
    slug: 'symbol',
    start: '## Symbol (`*.sym.toml`)',
    title: 'Symbols',
    summary: 'The *.sym.toml file: pins, graphics, generated box bodies, multi-unit symbols and logic levels for the signal check.',
    group: 'Parts',
  },
  {
    slug: 'footprint',
    start: '## Footprint (`*.fp.toml`)',
    title: 'Footprints',
    summary: 'The *.fp.toml file: pad rows, pad shapes and layers, edge pads, zone connections, courtyards, silk and 3D models.',
    group: 'Parts',
  },
  {
    slug: 'graphics',
    start: '## Graphics',
    title: 'Graphics',
    summary: 'The shapes symbols, footprints and layouts share: lines, rectangles, polylines, polygons, circles, arcs and text.',
    group: 'Parts',
  },
  {
    slug: 'schematic',
    start: '## Schematic (`*.sch.toml`)',
    title: 'Schematics',
    summary: 'The *.sch.toml file: placed parts, nets as lists of pins, net classes, rails and the signal level check, and sheets for large designs.',
    group: 'Schematic and layout',
  },
  {
    slug: 'layout',
    start: '## Layout (`*.pcb.toml`)',
    title: 'Layouts',
    summary: 'The *.pcb.toml file: placements, tracks, vias, fanouts, stitching, zones, cutouts, silk, artwork, test access and the version watermark.',
    group: 'Schematic and layout',
  },
  {
    slug: 'placement',
    start: '### Placement',
    title: 'Automatic placement',
    summary: 'agentee place: connectors on edges, large chips central, decoupling caps at their pins, then legalised and refined.',
    group: 'Schematic and layout',
  },
  {
    slug: 'routing',
    start: '### Autorouting',
    title: 'Autorouting',
    summary: 'agentee route, tie, tune and neck: grid routing that keeps class widths, clearances and vias, plane ties, length matching and neck-downs.',
    group: 'Schematic and layout',
  },
  {
    slug: 'interfaces',
    start: '### Interfaces',
    title: 'Interfaces',
    summary: 'What a link must meet, from USB 3 to a 50 ohm RF line: impedance, skew, length, vias, stubs, reference planes and return vias.',
    group: 'Schematic and layout',
  },
  {
    slug: 'viewer',
    start: '### Editing in the viewer',
    title: 'Editing in the viewer',
    summary: 'Moving parts, routing tracks and placing vias by hand in agentee view, saved back into the same TOML.',
    group: 'Schematic and layout',
  },
  {
    slug: 'fdtd',
    start: '## Simulation (`*.sim.toml`)',
    title: 'FDTD simulation',
    summary: 'A full-wave FDTD run of a layout on the GPU with lumped ports on pads, giving S-parameters as JSON and Touchstone.',
    group: 'Simulation',
  },
  {
    slug: 'channel',
    start: '### Channel (`kind = "channel"`)',
    title: 'Channel and eye',
    summary: 'A bit stream through an S-parameter path with CTLE, DFE and IBIS drivers and receivers, read as an eye.',
    group: 'Simulation',
  },
  {
    slug: 'pdn',
    start: '### PDN (`kind = "pdn"`)',
    title: 'Power distribution network',
    summary: 'The impedance of a power rail from its sinks, decaps and VRM against a target, with the anti-resonances to fix.',
    group: 'Simulation',
  },
  {
    slug: 'sparam',
    start: '### Analysing a result',
    title: 'Analysing S-parameters',
    summary: 'TDR, mixed-mode pairs, crosstalk, passivity and reciprocity from any FDTD or cascade result.',
    group: 'Simulation',
  },
  {
    slug: 'fdtd-losses',
    start: '### Losses in the FDTD',
    title: 'Losses in the FDTD',
    summary: 'Causal dielectric loss, surface impedance with skin effect, roughness and ENIG nickel, and the edge corrections of the mesh.',
    group: 'Simulation',
  },
  {
    slug: 'fields',
    start: '### Field maps and emissions',
    title: 'Field maps and emissions',
    summary: 'E and H field maps in the first prepreg and the far field, with radiated power and the field at 3 m against FCC class B.',
    group: 'Simulation',
  },
  {
    slug: 'cascade',
    start: '### Cascade (`kind = "cascade"`)',
    title: 'Cascade',
    summary: 'Vendor S-parameters, noise and linearity dropped into a board sim: gain, noise figure, IIP3, P1dB, SFDR and stability.',
    group: 'Simulation',
  },
  {
    slug: 'dc',
    start: '### DC drop (`kind = "dc"`)',
    title: 'DC drop',
    summary: 'Every copper layer solved as a resistive sheet: drop, current density, load voltages and the busiest vias.',
    group: 'Simulation',
  },
  {
    slug: 'thermal',
    start: '### Thermal (`kind = "thermal"`)',
    title: 'Thermal',
    summary: 'Steady state conduction through FR4, copper and vias with convection from both faces, solved on the GPU.',
    group: 'Simulation',
  },
  {
    slug: 'logic',
    start: '### Logic (`kind = "logic"`)',
    title: 'Logic simulation',
    summary: 'An event-driven sim of a schematic’s digital parts: 74 series models, primitives, stimulus, assertions, setup and hold, VCD out.',
    group: 'Simulation',
  },
  {
    slug: 'kicad-import',
    start: '## Importing a KiCad board',
    title: 'Importing a KiCad board',
    summary: 'agentee import board turns a .kicad_pcb into a board spec, layout, netlist schematic, footprints and symbols.',
    group: 'Output',
  },
  {
    slug: 'fab',
    start: '## Fab package',
    title: 'Fab package',
    summary: 'The Gerbers, drill files, BOM, placement, IPC-D-356 netlist, test points and fab notes agentee fab writes.',
    group: 'Output',
  },
  {
    slug: 'distributors',
    start: '## Distributors',
    title: 'Distributors and pricing',
    summary: 'agentee parts: BOM pricing at Mouser and Farnell and cheaper parts that drop in without a downgrade.',
    group: 'Output',
  },
];
