export const OVERRIDES: Record<string, Record<string, string>> = {
  'Out the door': {
    de: 'Ab in die Fertigung',
    fr: 'Direction la fabrication',
    es: 'Listo para fabricar',
    it: 'Pronto per la produzione',
    pt: 'Pronto para fabricar',
    nl: 'Klaar voor productie',
    pl: 'Gotowe do produkcji',
    ru: 'Готово к производству',
    ja: '製造へ',
    zh: '交付制造',
  },
  'Check knows the fab': {
    de: 'Die Prüfung kennt den Fertiger',
    fr: 'La vérification connaît le fabricant',
    es: 'La verificación conoce al fabricante',
    it: 'La verifica conosce il produttore',
    pt: 'A verificação conhece o fabricante',
    nl: 'De controle kent de fabrikant',
    pl: 'Sprawdzanie zna producenta',
    ru: 'Проверка знает правила завода',
    ja: 'チェックは基板メーカーのルールを把握しています',
    zh: '检查了解板厂的规则',
  },
  Edit: {
    de: 'Bearbeiten',
    fr: 'Modifier',
    es: 'Editar',
    it: 'Modifica',
    pt: 'Editar',
    nl: 'Bewerken',
    pl: 'Edytuj',
    ru: 'Правка',
    ja: '編集',
    zh: '编辑',
  },
  Check: {
    de: 'Prüfen',
    fr: 'Vérifier',
    es: 'Verificar',
    it: 'Verifica',
    pt: 'Verificar',
    nl: 'Controleren',
    pl: 'Sprawdź',
    ru: 'Проверка',
    ja: 'チェック',
    zh: '检查',
  },
  Look: {
    de: 'Ansehen',
    fr: 'Regarder',
    es: 'Mirar',
    it: 'Guarda',
    pt: 'Ver',
    nl: 'Bekijken',
    pl: 'Obejrzyj',
    ru: 'Просмотр',
    ja: '確認',
    zh: '查看',
  },
  Measure: {
    de: 'Messen',
    fr: 'Mesurer',
    es: 'Medir',
    it: 'Misura',
    pt: 'Medir',
    nl: 'Meten',
    pl: 'Zmierz',
    ru: 'Измерение',
    ja: '計測',
    zh: '测量',
  },
  Ship: {
    de: 'Fertigung',
    fr: 'Fabrication',
    es: 'Fabricación',
    it: 'Produzione',
    pt: 'Fabrico',
    nl: 'Productie',
    pl: 'Produkcja',
    ru: 'Производство',
    ja: '製造',
    zh: '制造',
  },
  Skill: {
    de: 'Skill',
    fr: 'Skill',
    es: 'Skill',
    it: 'Skill',
    pt: 'Skill',
    nl: 'Skill',
    pl: 'Skill',
    ru: 'Skill',
    ja: 'スキル',
    zh: '技能',
  },
  'Worked examples': {
    de: 'Ausgearbeitete Beispiele',
    fr: 'Exemples complets',
    es: 'Ejemplos completos',
    it: 'Esempi completi',
    pt: 'Exemplos completos',
    nl: 'Uitgewerkte voorbeelden',
    pl: 'Kompletne przykłady',
    ru: 'Готовые примеры',
    ja: '作例',
    zh: '完整示例',
  },
  'Worked designs': {
    de: 'Ausgearbeitete Designs',
    fr: 'Conceptions complètes',
    es: 'Diseños completos',
    it: 'Progetti completi',
    pt: 'Projetos completos',
    nl: 'Uitgewerkte ontwerpen',
    pl: 'Kompletne projekty',
    ru: 'Готовые проекты',
    ja: '設計の作例',
    zh: '完整设计示例',
  },
  'Coming from KiCad': {
    fr: 'Si vous venez de KiCad',
    pt: 'Para quem vem do KiCad',
  },
};
